# Generated by Django 2.2.10 on 2020-04-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='idpersona',
            field=models.SmallIntegerField(),
        ),
    ]
